### PR TITLE
Date casting return native Date JS object instead of moment

### LINKED ISSUE #33: Reason for dates being moment objects?
I'm giving jsontableschema-js a try in a project, I'm surprised that the 'data' type returns moment objects.  Any reason not to return JS date objects?  If you are using moment just for parsing how about returning the `.toDate()` output.

### PR DESCRIPTION
**Pull request by zhenyab**
@roll, @pwalsh, @Hypercubed

Accordingly to the discussion in the issue (it fixes #33) I just made those changes.

### CODE REVIEW

**Comment by roll** [comment]
@zhenyab 
looks good to me

**Comment by akariv** [comment]
Not to be nitpickey, but perhaps is better to complement such API breaking changes with a major version update as well. 
@pwalsh @zhenyab @roll

**Comment by pwalsh** [comment]
@akariv 100% agreed, but we haven't pushed a version yet as far as I know.

**Comment by roll** [comment]
@akariv 
This is not really public for now

**Comment by akariv** [comment]
I think it's still better to update the version in place and not rely on our collective memories to try and collect what changed between the next `npm publish` (whenever that's going to happen) and the one that was around May this year...

**Comment by Hypercubed** [comment]
This is great.  I was playing with date parsing yesterday.  Can we use only `d3-time-format` instead of moment? I believe the three formats we need for strict ISO 8610 parsing are:

```
datetime: d3timeFormat.utcParse('%Y-%m-%dT%H:%M:%SZ')
date: d3timeFormat.utcParse('%Y-%m-%d')
time: d3timeFormat.utcParse('%H:%M:%S')
```

**Comment by zhenyab** [comment]
d3 was introduced to dealing with **%Y** kind of formatting only (started with %), which moment does not know to parse. If to stay only with d3, it means need to strictly force to provide format string with **%** always. But usually formats are very different.

**Comment by Hypercubed** [comment]
@zhenyab I'm not following you on this one.  The defaults format for all three types (datetime, date, and time) are all strict ISO 8610 UTC.  Currently, moment is being used to parse these types, but d3, I believe, can parse these just as well (see comment above).  I think the only benefit of the moment API is the `isValid()` function, which, when in d3 becomes a null check (see https://github.com/frictionlessdata/jsontableschema-js/blob/95ebf28500d9eac401a84e809fe9583ba8ed2848/src/types.js#L378).

Currently, the only other patterns (via `fmt:pattern`) usable according to the spec are "standard Python / C strptime" (see http://specs.frictionlessdata.io/json-table-schema/#date) and these are parsed using d3 anyway (see https://github.com/frictionlessdata/jsontableschema-js/blob/95ebf28500d9eac401a84e809fe9583ba8ed2848/src/types.js#L377).  So why not use the d3time for everything?

I think this line https://github.com/frictionlessdata/jsontableschema-js#L381 is completely superfluous since `d3time.timeParse` returns a date already.

BTW, I have nothing against moment.  Just trying to see if we can get one less dependency.

**Comment by zhenyab** [comment]
I agree with you, if no need to use moment, why need to use it? Just need to understand if we can do it. Moment stay from previous version.

You are right regarding the line 381. I will fix it.

Please take a look here https://github.com/frictionlessdata/jsontableschema-js/pull/20

**Comment by akariv** [comment]
The benefits of using moment are that it knows to parse dates with good heuristics and without having to specify the exact format.

See for example here: https://github.com/frictionlessdata/jsontableschema-js/blob/master/test/types.js#L358

**Comment by Hypercubed** [comment]
@akariv My interpretation of the JSON Table Schema spec is that the `default` formats are strict.  In fact `datetime` only accepts "YYYY-MM-DDThh:mm:ssZ" not even "YYYY-MM-DDThh:mm:ss.sssZ".  In these cases, the d3 library works as expected.

The `fmt:PATTERN` format also is strict, using percent notation, and, as noted in #20, d3time is needed in this case.

I think the only use case for `moment` may be for the `any` format.  In the test case you pointed out I think `d => new Date(d)` would work just as well.  But perhaps moment is better here.

P.S. I hope this discussion is helpfull.  At the moment I am using my own implementation (here: https://github.com/Hypercubed/chi-datapackage/blob/master/src/lib/types.js) but hope to delegate to jsontableschema-js when appropriate.

**Pull request merged**
