### PR TITLE
Add support for percent signs (basically ignoring them)

### PR DESCRIPTION
**Pull request by akariv**

### CODE REVIEW

**Comment by pwalsh** [comment]
@zhenyab Can you add this to the new codebase, and then close the PR (as it cant me merged).

cc @akariv

**Comment by zhenyab** [comment]
@pwalsh, @akariv 1000% and 100% currently can be casted only to integer type, because after removing '%' sign it is become integer. Number type can be only float values.

**Comment by akariv** [comment]
So basically '1000' is an invalid value for the `number` datatype?

**Comment by pwalsh** [comment]
@zhenyab if we have `100` in a number column, it should be valid (example expected behaviour: 100 can be cast to number, but 100.00 cannot be cast to integer).

**Comment by zhenyab** [comment]
Ok! So, to be sure, number type can be any type of number like integer or float, or this behavior is valid only if it tries to cast field of type number only?

**Comment by pwalsh** [comment]
Number type can be any type of number.

**Comment by zhenyab** [comment]
I port percentage fix into 'feature/docs' branch and fixed number type as well

**Comment by pwalsh** [comment]
@akariv I'm closing this: it is now on master in the refactored code base. A few more changes this week and we'll publish a new version to npm.

**Pull request closed without merging**
